/* ===============================================================
   Offline cache.

   The app shell is cached per build, so a deploy installs as one
   consistent version and the page offers "Reload" to switch.
   Exercise images live in a separate cache and are only re-fetched
   when their content changes.

   tools/build.py rewrites the block between the BUILD markers. Run it
   before every deploy; a changed BUILD_ID is what tells installed
   apps there is an update.
=============================================================== */

/* BUILD:START */
const BUILD_ID = "31f554ce31";
const SHELL_FILES = [
 "./",
 "index.html",
 "manifest.json",
 "css/app.css",
 "js/app.js",
 "js/catalog.js",
 "js/core.js",
 "js/editor.js",
 "js/history.js",
 "js/images.js",
 "js/progress.js",
 "js/search.js",
 "js/sections.js",
 "js/share.js",
 "js/stats.js",
 "js/templates.js",
 "js/timer.js",
 "js/today.js",
 "js/ui.js",
 "js/you.js",
 "assets/icon-192.png",
 "assets/icon-512.png",
 "assets/apple-touch-icon.png",
 "assets/mascot-web.jpg"
];
const IMAGE_FILES = {
 "assets/Exercises/thumb/54-abductor-machine.jpg": "c51a3df7",
 "assets/Exercises/thumb/ab-wheel-rollout.jpg": "f03d128d",
 "assets/Exercises/thumb/adductor-machine.jpg": "8c802bf7",
 "assets/Exercises/thumb/air-assault-bike.jpg": "64d714a5",
 "assets/Exercises/thumb/arc-trainer.jpg": "f24c3198",
 "assets/Exercises/thumb/arm-circles.jpg": "80e678c8",
 "assets/Exercises/thumb/arnold-press.jpg": "97f36b9e",
 "assets/Exercises/thumb/assisted-machine-dip.jpg": "1398bd3c",
 "assets/Exercises/thumb/assisted-pull-up.jpg": "d3c5b560",
 "assets/Exercises/thumb/band-pull-apart.jpg": "04c61ab4",
 "assets/Exercises/thumb/band-shoulder-pass-through.jpg": "be8d4d30",
 "assets/Exercises/thumb/banded-lateral-walk.jpg": "912f5841",
 "assets/Exercises/thumb/barbell-back-squat.jpg": "983d2ec4",
 "assets/Exercises/thumb/barbell-bench-press.jpg": "f420b55e",
 "assets/Exercises/thumb/barbell-bent-over-row.jpg": "9db56a09",
 "assets/Exercises/thumb/barbell-ez-bar-curl.jpg": "d8e9a8d3",
 "assets/Exercises/thumb/barbell-glute-bridge.jpg": "4ea18e58",
 "assets/Exercises/thumb/barbell-hip-thrust.jpg": "d7febf6f",
 "assets/Exercises/thumb/barbell-romanian-deadlift.jpg": "5cba5fde",
 "assets/Exercises/thumb/barbell-snatch.jpg": "f2bad3d7",
 "assets/Exercises/thumb/barbell-thruster.jpg": "986878d6",
 "assets/Exercises/thumb/battle-rope-waves.jpg": "575f8807",
 "assets/Exercises/thumb/bear-crawl.jpg": "e9101c8e",
 "assets/Exercises/thumb/belt-squat.jpg": "39c828ea",
 "assets/Exercises/thumb/bench-dip.jpg": "dd787134",
 "assets/Exercises/thumb/bicycle-crunch.jpg": "9e458ce0",
 "assets/Exercises/thumb/bird-dog.jpg": "350a9611",
 "assets/Exercises/thumb/bodyweight-glute-bridge.jpg": "21bea08a",
 "assets/Exercises/thumb/bodyweight-squat.jpg": "49f7affa",
 "assets/Exercises/thumb/bodyweight-triceps-extension.jpg": "f09f1925",
 "assets/Exercises/thumb/box-jump.jpg": "04246d5f",
 "assets/Exercises/thumb/box-squat.jpg": "eeb21734",
 "assets/Exercises/thumb/broad-jump.jpg": "02f2e6b5",
 "assets/Exercises/thumb/bulgarian-split-squat.jpg": "017c060c",
 "assets/Exercises/thumb/burpee.jpg": "40767c5c",
 "assets/Exercises/thumb/butterfly-adductor-stretch.jpg": "61d2e88e",
 "assets/Exercises/thumb/cable-crunch.jpg": "1fac1236",
 "assets/Exercises/thumb/cable-external-rotation.jpg": "5c3fd373",
 "assets/Exercises/thumb/cable-front-raise.jpg": "c07939d6",
 "assets/Exercises/thumb/cable-glute-kickback.jpg": "72c07aaa",
 "assets/Exercises/thumb/cable-hip-abduction.jpg": "a842f217",
 "assets/Exercises/thumb/cable-hip-adduction.jpg": "72e505e4",
 "assets/Exercises/thumb/cable-internal-rotation.jpg": "c1d1d866",
 "assets/Exercises/thumb/cable-lateral-raise.jpg": "40734278",
 "assets/Exercises/thumb/cable-pull-through.jpg": "1c0a3fef",
 "assets/Exercises/thumb/cable-triceps-kickback.jpg": "64030ad2",
 "assets/Exercises/thumb/cable-wood-chop.jpg": "43b40f15",
 "assets/Exercises/thumb/calf-stretch.jpg": "0cad327a",
 "assets/Exercises/thumb/captains-chair-knee-raise.jpg": "de8d0a08",
 "assets/Exercises/thumb/cat-cow.jpg": "0ff746a7",
 "assets/Exercises/thumb/chest-dip.jpg": "c5374322",
 "assets/Exercises/thumb/chest-supported-dumbbell-row.jpg": "afc45ed5",
 "assets/Exercises/thumb/chest-supported-machine-row.jpg": "eb8c5497",
 "assets/Exercises/thumb/chest-supported-t-bar-row.jpg": "886c50d4",
 "assets/Exercises/thumb/childs-pose.jpg": "d56fe436",
 "assets/Exercises/thumb/chin-up.jpg": "0f0ed2e5",
 "assets/Exercises/thumb/clean-and-jerk.jpg": "f0868136",
 "assets/Exercises/thumb/close-grip-barbell-bench-press.jpg": "777d4b23",
 "assets/Exercises/thumb/concentration-curl.jpg": "3c597f7e",
 "assets/Exercises/thumb/copenhagen-plank.jpg": "61193c49",
 "assets/Exercises/thumb/curtsy-lunge.jpg": "b13ccf19",
 "assets/Exercises/thumb/dead-bug.jpg": "8045aea9",
 "assets/Exercises/thumb/dead-hang.jpg": "dd76720c",
 "assets/Exercises/thumb/deadlift.jpg": "80bfc514",
 "assets/Exercises/thumb/decline-dumbbell-press.jpg": "1a4d777e",
 "assets/Exercises/thumb/decline-press.jpg": "b747bf87",
 "assets/Exercises/thumb/decline-push-up.jpg": "bb119eb8",
 "assets/Exercises/thumb/decline-sit-up.jpg": "6512a326",
 "assets/Exercises/thumb/degree-back-extension.jpg": "14d65b99",
 "assets/Exercises/thumb/diamond-close-grip-push-up.jpg": "edc77d08",
 "assets/Exercises/thumb/donkey-calf-raise.jpg": "77a923b7",
 "assets/Exercises/thumb/dumbbell-bicep-curl.jpg": "9b2d74fe",
 "assets/Exercises/thumb/dumbbell-chest-fly.jpg": "280ae74b",
 "assets/Exercises/thumb/dumbbell-chest-press.jpg": "85fca254",
 "assets/Exercises/thumb/dumbbell-clean-and-press.jpg": "68b4da55",
 "assets/Exercises/thumb/dumbbell-floor-press.jpg": "b9bdaa3c",
 "assets/Exercises/thumb/dumbbell-front-raise.jpg": "113717e9",
 "assets/Exercises/thumb/dumbbell-hip-thrust.jpg": "279f0795",
 "assets/Exercises/thumb/dumbbell-pullover.jpg": "6ce12b4a",
 "assets/Exercises/thumb/dumbbell-romanian-deadlift.jpg": "ef21cf59",
 "assets/Exercises/thumb/dumbbell-squat.jpg": "e9d079ae",
 "assets/Exercises/thumb/dumbbell-thruster.jpg": "a669bdcc",
 "assets/Exercises/thumb/dumbbell-triceps-kickback.jpg": "40700cbb",
 "assets/Exercises/thumb/elliptical-cross-trainer.jpg": "3836c419",
 "assets/Exercises/thumb/face-pull.jpg": "b075ac1c",
 "assets/Exercises/thumb/farmers-carry.jpg": "241f9633",
 "assets/Exercises/thumb/flat-dumbbell-press.jpg": "f07fa0a0",
 "assets/Exercises/thumb/floor-crunch.jpg": "7ac82ae7",
 "assets/Exercises/thumb/foam-roll-calves.jpg": "724033fd",
 "assets/Exercises/thumb/foam-roll-glutes-piriformis.jpg": "f6d1473c",
 "assets/Exercises/thumb/foam-roll-lats.jpg": "48953d62",
 "assets/Exercises/thumb/foam-roll-quadriceps.jpg": "f5cb9f48",
 "assets/Exercises/thumb/forward-lunge.jpg": "e35dadd2",
 "assets/Exercises/thumb/front-squat.jpg": "7865b3a3",
 "assets/Exercises/thumb/glute-ham-raise.jpg": "f871a2ec",
 "assets/Exercises/thumb/glute-kickback-machine.jpg": "1354e4c6",
 "assets/Exercises/thumb/goblet-squat.jpg": "d6bdaac2",
 "assets/Exercises/thumb/good-morning.jpg": "abdddd3e",
 "assets/Exercises/thumb/hack-squat.jpg": "a98bcc98",
 "assets/Exercises/thumb/hammer-curl.jpg": "7310c68c",
 "assets/Exercises/thumb/hamstring-stretch.jpg": "dfd104e8",
 "assets/Exercises/thumb/hanging-knee-raise.jpg": "477a973b",
 "assets/Exercises/thumb/hanging-leg-raise.jpg": "3ab6bf9f",
 "assets/Exercises/thumb/heel-walks.jpg": "436ef094",
 "assets/Exercises/thumb/high-to-low-cable-fly.jpg": "d3a594db",
 "assets/Exercises/thumb/hip-flexor-stretch.jpg": "860ec0cb",
 "assets/Exercises/thumb/hollow-body-hold.jpg": "8e75e951",
 "assets/Exercises/thumb/incline-barbell-bench-press.jpg": "e4b2ae55",
 "assets/Exercises/thumb/incline-dumbbell-curl.jpg": "450c33ea",
 "assets/Exercises/thumb/incline-dumbbell-fly.jpg": "357c89cc",
 "assets/Exercises/thumb/incline-dumbbell-press.jpg": "8b85edb9",
 "assets/Exercises/thumb/incline-push-up.jpg": "1bd648a8",
 "assets/Exercises/thumb/incline-treadmill.jpg": "111d3d8f",
 "assets/Exercises/thumb/incline-y-raise.jpg": "ae704430",
 "assets/Exercises/thumb/indoor-spin-cycle.jpg": "33b3a391",
 "assets/Exercises/thumb/inverted-row-trx-row.jpg": "8bc35920",
 "assets/Exercises/thumb/jump-rope-skipping.jpg": "736c4027",
 "assets/Exercises/thumb/jump-squat.jpg": "8331909f",
 "assets/Exercises/thumb/jumping-jack.jpg": "870e90e3",
 "assets/Exercises/thumb/jumping-lunge.jpg": "332d69ce",
 "assets/Exercises/thumb/kettlebell-swing.jpg": "78701a2e",
 "assets/Exercises/thumb/knee-push-up.jpg": "1218ca35",
 "assets/Exercises/thumb/landmine-chest-press.jpg": "02188559",
 "assets/Exercises/thumb/landmine-press.jpg": "e6766551",
 "assets/Exercises/thumb/landmine-row.jpg": "632c3072",
 "assets/Exercises/thumb/lat-pulldown.jpg": "c9fcf959",
 "assets/Exercises/thumb/lateral-lunge-cossack-squat.jpg": "198e5c8d",
 "assets/Exercises/thumb/lateral-raise.jpg": "3469c708",
 "assets/Exercises/thumb/leg-extension.jpg": "4c828e86",
 "assets/Exercises/thumb/leg-press-calf-raise.jpg": "f73c25ee",
 "assets/Exercises/thumb/leg-press.jpg": "9793c46f",
 "assets/Exercises/thumb/leg-swings.jpg": "bc8f1969",
 "assets/Exercises/thumb/low-to-high-cable-crossover.jpg": "4218d68a",
 "assets/Exercises/thumb/lying-ez-bar-triceps-extension.jpg": "de077239",
 "assets/Exercises/thumb/lying-leg-curl.jpg": "0321ae21",
 "assets/Exercises/thumb/lying-leg-raise.jpg": "896d0485",
 "assets/Exercises/thumb/machine-biceps-curl.jpg": "afe158c9",
 "assets/Exercises/thumb/machine-crunch.jpg": "397379c3",
 "assets/Exercises/thumb/machine-lateral-raise.jpg": "7b465cf2",
 "assets/Exercises/thumb/machine-pullover.jpg": "5f90ed54",
 "assets/Exercises/thumb/machine-shoulder-press.jpg": "3b61d982",
 "assets/Exercises/thumb/medicine-ball-slam.jpg": "9733e8dc",
 "assets/Exercises/thumb/mountain-climber.jpg": "95c7616b",
 "assets/Exercises/thumb/neutral-close-grip-lat-pulldown.jpg": "e6429337",
 "assets/Exercises/thumb/nordic-hamstring-curl.jpg": "c55338bc",
 "assets/Exercises/thumb/one-arm-dumbbell-row.jpg": "e2a7fd2d",
 "assets/Exercises/thumb/overhead-cable-triceps-extension.jpg": "42aa798d",
 "assets/Exercises/thumb/overhead-dumbbell-extension.jpg": "f18e7666",
 "assets/Exercises/thumb/overhead-tricep-extension.jpg": "9fe385b8",
 "assets/Exercises/thumb/pallof-press.jpg": "05b2c9cd",
 "assets/Exercises/thumb/pec-deck.jpg": "df3c2daa",
 "assets/Exercises/thumb/pendlay-row.jpg": "cc859f31",
 "assets/Exercises/thumb/pendulum-squat.jpg": "595ca592",
 "assets/Exercises/thumb/pike-push-up.jpg": "28c465f6",
 "assets/Exercises/thumb/pistol-squat.jpg": "395a60e7",
 "assets/Exercises/thumb/plank-shoulder-tap.jpg": "3180fb89",
 "assets/Exercises/thumb/plank.jpg": "0c94e6a4",
 "assets/Exercises/thumb/plate-pinch-hold.jpg": "0f5c8b50",
 "assets/Exercises/thumb/power-clean.jpg": "abaf302c",
 "assets/Exercises/thumb/preacher-curl.jpg": "65e316b5",
 "assets/Exercises/thumb/pull-ups.jpg": "9872293e",
 "assets/Exercises/thumb/push-press.jpg": "ef133caf",
 "assets/Exercises/thumb/push-ups.jpg": "0a7b765c",
 "assets/Exercises/thumb/rack-pull.jpg": "8588d23a",
 "assets/Exercises/thumb/rear-delt-fly.jpg": "d4c412c7",
 "assets/Exercises/thumb/recumbent-stationary-bike.jpg": "eec2d6dd",
 "assets/Exercises/thumb/renegade-row.jpg": "24c7729e",
 "assets/Exercises/thumb/reverse-crunch.jpg": "8e81b5a8",
 "assets/Exercises/thumb/reverse-curl.jpg": "0ca3d567",
 "assets/Exercises/thumb/reverse-hyperextension.jpg": "23d9ddb2",
 "assets/Exercises/thumb/reverse-lunge.jpg": "93546160",
 "assets/Exercises/thumb/reverse-pec-deck.jpg": "94b52b14",
 "assets/Exercises/thumb/reverse-wrist-curl.jpg": "53559e5e",
 "assets/Exercises/thumb/rowing-ergometer.jpg": "d2c3592a",
 "assets/Exercises/thumb/russian-twist.jpg": "39b9833c",
 "assets/Exercises/thumb/seated-cable-fly.jpg": "843944d7",
 "assets/Exercises/thumb/seated-cable-row.jpg": "34bab9f0",
 "assets/Exercises/thumb/seated-calf-raise.jpg": "9affba33",
 "assets/Exercises/thumb/seated-dumbbell-shoulder-press.jpg": "f9a27da0",
 "assets/Exercises/thumb/seated-leg-curl.jpg": "2a5011a8",
 "assets/Exercises/thumb/seated-machine-chest-press.jpg": "d524562d",
 "assets/Exercises/thumb/seated-machine-row.jpg": "24adb6c8",
 "assets/Exercises/thumb/shrugs.jpg": "9dd61152",
 "assets/Exercises/thumb/side-plank.jpg": "69e5d5a5",
 "assets/Exercises/thumb/single-arm-cable-pushdown.jpg": "60b51756",
 "assets/Exercises/thumb/single-arm-cable-row.jpg": "fee49d1a",
 "assets/Exercises/thumb/single-arm-dumbbell-row.jpg": "a9820210",
 "assets/Exercises/thumb/single-arm-lat-pulldown.jpg": "3ba826be",
 "assets/Exercises/thumb/single-leg-calf-raise.jpg": "6074a2c8",
 "assets/Exercises/thumb/single-leg-glute-bridge.jpg": "e67239b9",
 "assets/Exercises/thumb/single-leg-press.jpg": "92f37ba3",
 "assets/Exercises/thumb/single-leg-romanian-deadlift.jpg": "248eb48b",
 "assets/Exercises/thumb/sissy-squat.jpg": "5a082a38",
 "assets/Exercises/thumb/sit-up.jpg": "6a068851",
 "assets/Exercises/thumb/skierg.jpg": "395825c0",
 "assets/Exercises/thumb/sled-pull-drag.jpg": "8dfbe432",
 "assets/Exercises/thumb/sled-push.jpg": "23264185",
 "assets/Exercises/thumb/smith-machine-bench-press.jpg": "ee9dfe66",
 "assets/Exercises/thumb/smith-machine-squat.jpg": "66cc7510",
 "assets/Exercises/thumb/spider-curl.jpg": "32e28db8",
 "assets/Exercises/thumb/split-squat.jpg": "d5c25ca9",
 "assets/Exercises/thumb/stairs.jpg": "e618ff99",
 "assets/Exercises/thumb/standing-barbell-overhead-press.jpg": "e7c9cc13",
 "assets/Exercises/thumb/standing-cable-fly-crossover.jpg": "c7a9bd35",
 "assets/Exercises/thumb/standing-calf-raise.jpg": "a83082e6",
 "assets/Exercises/thumb/standing-dumbbell-curl.jpg": "7c2a9f2f",
 "assets/Exercises/thumb/standing-leg-curl.jpg": "6984e37b",
 "assets/Exercises/thumb/standing-quadriceps-stretch.jpg": "efb6f00d",
 "assets/Exercises/thumb/step-up.jpg": "aac8ee4c",
 "assets/Exercises/thumb/stiff-legged-deadlift.jpg": "85651df0",
 "assets/Exercises/thumb/straight-arm-cable-pulldown.jpg": "e6cbbd5a",
 "assets/Exercises/thumb/suitcase-carry.jpg": "25fb168c",
 "assets/Exercises/thumb/sumo-deadlift.jpg": "e187c0a2",
 "assets/Exercises/thumb/superman.jpg": "146e10b1",
 "assets/Exercises/thumb/thoracic-rotation-open-book.jpg": "0d345a28",
 "assets/Exercises/thumb/trap-bar-deadlift.jpg": "fc10af56",
 "assets/Exercises/thumb/treadmill-run.jpg": "5d468ffe",
 "assets/Exercises/thumb/treadmill-walk.jpg": "bae199bd",
 "assets/Exercises/thumb/tricep-pushdown.jpg": "45469768",
 "assets/Exercises/thumb/tricep-rope-pushdown.jpg": "18b8059f",
 "assets/Exercises/thumb/turkish-get-up.jpg": "824da41d",
 "assets/Exercises/thumb/underhand-lat-pulldown.jpg": "1f9e786a",
 "assets/Exercises/thumb/upper-body-ergometer.jpg": "71e2f333",
 "assets/Exercises/thumb/upright-row.jpg": "6b823855",
 "assets/Exercises/thumb/upright-stationary-bike.jpg": "eb42a9c8",
 "assets/Exercises/thumb/v-up.jpg": "fac10c28",
 "assets/Exercises/thumb/walking-lunges-with-dumbbells.jpg": "527b0746",
 "assets/Exercises/thumb/wall-ball.jpg": "a18068bb",
 "assets/Exercises/thumb/wall-sit.jpg": "f0621ca3",
 "assets/Exercises/thumb/weighted-plank.jpg": "2d71c7f0",
 "assets/Exercises/thumb/wide-stance-goblet-squat.jpg": "5bb406b4",
 "assets/Exercises/thumb/worlds-greatest-stretch.jpg": "ee621e59",
 "assets/Exercises/thumb/wrist-curl.jpg": "9bed4b26",
 "assets/Exercises/thumb/wrist-roller.jpg": "ce7a0085",
 "assets/Exercises/thumb/zottman-curl.jpg": "0d074516",
 "assets/Exercises/web/54-abductor-machine.jpg": "12397921",
 "assets/Exercises/web/ab-wheel-rollout.jpg": "f5d9e593",
 "assets/Exercises/web/adductor-machine.jpg": "1ee0d96f",
 "assets/Exercises/web/air-assault-bike.jpg": "7fa9e4dc",
 "assets/Exercises/web/arc-trainer.jpg": "bc9eec67",
 "assets/Exercises/web/arm-circles.jpg": "c0c9630e",
 "assets/Exercises/web/arnold-press.jpg": "badefa25",
 "assets/Exercises/web/assisted-machine-dip.jpg": "7822e00c",
 "assets/Exercises/web/assisted-pull-up.jpg": "ec7669f6",
 "assets/Exercises/web/band-pull-apart.jpg": "ac56d8fb",
 "assets/Exercises/web/band-shoulder-pass-through.jpg": "e2d20d73",
 "assets/Exercises/web/banded-lateral-walk.jpg": "9278162c",
 "assets/Exercises/web/barbell-back-squat.jpg": "2e2c47f6",
 "assets/Exercises/web/barbell-bench-press.jpg": "381733da",
 "assets/Exercises/web/barbell-bent-over-row.jpg": "220313d8",
 "assets/Exercises/web/barbell-ez-bar-curl.jpg": "ad880d8b",
 "assets/Exercises/web/barbell-glute-bridge.jpg": "fa64be3f",
 "assets/Exercises/web/barbell-hip-thrust.jpg": "596d4b26",
 "assets/Exercises/web/barbell-romanian-deadlift.jpg": "70907099",
 "assets/Exercises/web/barbell-snatch.jpg": "9483bfdf",
 "assets/Exercises/web/barbell-thruster.jpg": "541c4486",
 "assets/Exercises/web/battle-rope-waves.jpg": "2e0fc2ec",
 "assets/Exercises/web/bear-crawl.jpg": "8425ff2b",
 "assets/Exercises/web/belt-squat.jpg": "2b52cb47",
 "assets/Exercises/web/bench-dip.jpg": "c172cc5a",
 "assets/Exercises/web/bicycle-crunch.jpg": "d2b1ee7b",
 "assets/Exercises/web/bird-dog.jpg": "61684f51",
 "assets/Exercises/web/bodyweight-glute-bridge.jpg": "98fa828c",
 "assets/Exercises/web/bodyweight-squat.jpg": "229033b5",
 "assets/Exercises/web/bodyweight-triceps-extension.jpg": "acf8b995",
 "assets/Exercises/web/box-jump.jpg": "ff413c22",
 "assets/Exercises/web/box-squat.jpg": "eb685963",
 "assets/Exercises/web/broad-jump.jpg": "6edd121f",
 "assets/Exercises/web/bulgarian-split-squat.jpg": "94039a86",
 "assets/Exercises/web/burpee.jpg": "11e7a435",
 "assets/Exercises/web/butterfly-adductor-stretch.jpg": "3dd348fc",
 "assets/Exercises/web/cable-crunch.jpg": "c3eedb2d",
 "assets/Exercises/web/cable-external-rotation.jpg": "1c7e825e",
 "assets/Exercises/web/cable-front-raise.jpg": "be274187",
 "assets/Exercises/web/cable-glute-kickback.jpg": "2f6f1771",
 "assets/Exercises/web/cable-hip-abduction.jpg": "3dd3eadc",
 "assets/Exercises/web/cable-hip-adduction.jpg": "bdcd07f2",
 "assets/Exercises/web/cable-internal-rotation.jpg": "b69293ba",
 "assets/Exercises/web/cable-lateral-raise.jpg": "98eb8f99",
 "assets/Exercises/web/cable-pull-through.jpg": "51fef56a",
 "assets/Exercises/web/cable-triceps-kickback.jpg": "f2125747",
 "assets/Exercises/web/cable-wood-chop.jpg": "9b10d82f",
 "assets/Exercises/web/calf-stretch.jpg": "441848ec",
 "assets/Exercises/web/captains-chair-knee-raise.jpg": "f35bef6c",
 "assets/Exercises/web/cat-cow.jpg": "1e3153f3",
 "assets/Exercises/web/chest-dip.jpg": "39d6b2a0",
 "assets/Exercises/web/chest-supported-dumbbell-row.jpg": "47cdc1c3",
 "assets/Exercises/web/chest-supported-machine-row.jpg": "3a9094ef",
 "assets/Exercises/web/chest-supported-t-bar-row.jpg": "23a744c4",
 "assets/Exercises/web/childs-pose.jpg": "ba618d43",
 "assets/Exercises/web/chin-up.jpg": "d3706c6d",
 "assets/Exercises/web/clean-and-jerk.jpg": "d4e83a55",
 "assets/Exercises/web/close-grip-barbell-bench-press.jpg": "23dfa411",
 "assets/Exercises/web/concentration-curl.jpg": "c3979d71",
 "assets/Exercises/web/copenhagen-plank.jpg": "80b6f4e6",
 "assets/Exercises/web/curtsy-lunge.jpg": "5844faa5",
 "assets/Exercises/web/dead-bug.jpg": "f6bc2098",
 "assets/Exercises/web/dead-hang.jpg": "8071c7ed",
 "assets/Exercises/web/deadlift.jpg": "6536beb4",
 "assets/Exercises/web/decline-dumbbell-press.jpg": "ef47db11",
 "assets/Exercises/web/decline-press.jpg": "0a3320a8",
 "assets/Exercises/web/decline-push-up.jpg": "22772d5d",
 "assets/Exercises/web/decline-sit-up.jpg": "33ab6271",
 "assets/Exercises/web/degree-back-extension.jpg": "b2e9d371",
 "assets/Exercises/web/diamond-close-grip-push-up.jpg": "a73af400",
 "assets/Exercises/web/donkey-calf-raise.jpg": "34aa7b2d",
 "assets/Exercises/web/dumbbell-bicep-curl.jpg": "f0b061ce",
 "assets/Exercises/web/dumbbell-chest-fly.jpg": "65e343d2",
 "assets/Exercises/web/dumbbell-chest-press.jpg": "15101811",
 "assets/Exercises/web/dumbbell-clean-and-press.jpg": "a366efd2",
 "assets/Exercises/web/dumbbell-floor-press.jpg": "f79d8097",
 "assets/Exercises/web/dumbbell-front-raise.jpg": "4031b3b3",
 "assets/Exercises/web/dumbbell-hip-thrust.jpg": "31902feb",
 "assets/Exercises/web/dumbbell-pullover.jpg": "c4a5b9e6",
 "assets/Exercises/web/dumbbell-romanian-deadlift.jpg": "83b76e2f",
 "assets/Exercises/web/dumbbell-squat.jpg": "feb957e8",
 "assets/Exercises/web/dumbbell-thruster.jpg": "7e6e9969",
 "assets/Exercises/web/dumbbell-triceps-kickback.jpg": "e127eed1",
 "assets/Exercises/web/elliptical-cross-trainer.jpg": "448c23a8",
 "assets/Exercises/web/face-pull.jpg": "0ff98e4e",
 "assets/Exercises/web/farmers-carry.jpg": "10b1d087",
 "assets/Exercises/web/flat-dumbbell-press.jpg": "b3594007",
 "assets/Exercises/web/floor-crunch.jpg": "f26e8a50",
 "assets/Exercises/web/foam-roll-calves.jpg": "5072e448",
 "assets/Exercises/web/foam-roll-glutes-piriformis.jpg": "6bd41c5b",
 "assets/Exercises/web/foam-roll-lats.jpg": "b460f6ee",
 "assets/Exercises/web/foam-roll-quadriceps.jpg": "ada9dad2",
 "assets/Exercises/web/forward-lunge.jpg": "b4fc0170",
 "assets/Exercises/web/front-squat.jpg": "351c9bb6",
 "assets/Exercises/web/glute-ham-raise.jpg": "92514add",
 "assets/Exercises/web/glute-kickback-machine.jpg": "af51afd9",
 "assets/Exercises/web/goblet-squat.jpg": "94967bb1",
 "assets/Exercises/web/good-morning.jpg": "a58218dd",
 "assets/Exercises/web/hack-squat.jpg": "fefd822d",
 "assets/Exercises/web/hammer-curl.jpg": "05e2ef10",
 "assets/Exercises/web/hamstring-stretch.jpg": "4574aabb",
 "assets/Exercises/web/hanging-knee-raise.jpg": "dabf33e1",
 "assets/Exercises/web/hanging-leg-raise.jpg": "34cb3ccb",
 "assets/Exercises/web/heel-walks.jpg": "3827149b",
 "assets/Exercises/web/high-to-low-cable-fly.jpg": "3fba05c0",
 "assets/Exercises/web/hip-flexor-stretch.jpg": "38045d47",
 "assets/Exercises/web/hollow-body-hold.jpg": "44b67f2a",
 "assets/Exercises/web/incline-barbell-bench-press.jpg": "df31ec58",
 "assets/Exercises/web/incline-dumbbell-curl.jpg": "1b1b040b",
 "assets/Exercises/web/incline-dumbbell-fly.jpg": "92135b79",
 "assets/Exercises/web/incline-dumbbell-press.jpg": "395ea4b0",
 "assets/Exercises/web/incline-push-up.jpg": "ae2af5c1",
 "assets/Exercises/web/incline-treadmill.jpg": "13560fe5",
 "assets/Exercises/web/incline-y-raise.jpg": "0ef93de5",
 "assets/Exercises/web/indoor-spin-cycle.jpg": "5b5ac8b0",
 "assets/Exercises/web/inverted-row-trx-row.jpg": "956162e8",
 "assets/Exercises/web/jump-rope-skipping.jpg": "811caa1c",
 "assets/Exercises/web/jump-squat.jpg": "511b47cb",
 "assets/Exercises/web/jumping-jack.jpg": "f75b29cb",
 "assets/Exercises/web/jumping-lunge.jpg": "530f7455",
 "assets/Exercises/web/kettlebell-swing.jpg": "bf31cba6",
 "assets/Exercises/web/knee-push-up.jpg": "12f0cef9",
 "assets/Exercises/web/landmine-chest-press.jpg": "b3f30035",
 "assets/Exercises/web/landmine-press.jpg": "1194f80a",
 "assets/Exercises/web/landmine-row.jpg": "afdf07a7",
 "assets/Exercises/web/lat-pulldown.jpg": "cc6192b5",
 "assets/Exercises/web/lateral-lunge-cossack-squat.jpg": "f14a6794",
 "assets/Exercises/web/lateral-raise.jpg": "218749a6",
 "assets/Exercises/web/leg-extension.jpg": "fe7992ce",
 "assets/Exercises/web/leg-press-calf-raise.jpg": "6ba601ac",
 "assets/Exercises/web/leg-press.jpg": "e4b07711",
 "assets/Exercises/web/leg-swings.jpg": "d30a38a8",
 "assets/Exercises/web/low-to-high-cable-crossover.jpg": "3fc086e7",
 "assets/Exercises/web/lying-ez-bar-triceps-extension.jpg": "8ae8c044",
 "assets/Exercises/web/lying-leg-curl.jpg": "cc145f09",
 "assets/Exercises/web/lying-leg-raise.jpg": "bafaa177",
 "assets/Exercises/web/machine-biceps-curl.jpg": "d95e4029",
 "assets/Exercises/web/machine-crunch.jpg": "4bb63726",
 "assets/Exercises/web/machine-lateral-raise.jpg": "098b6c40",
 "assets/Exercises/web/machine-pullover.jpg": "6d3a78c9",
 "assets/Exercises/web/machine-shoulder-press.jpg": "7cd8fb32",
 "assets/Exercises/web/medicine-ball-slam.jpg": "933bb7fc",
 "assets/Exercises/web/mountain-climber.jpg": "de6c30bc",
 "assets/Exercises/web/neutral-close-grip-lat-pulldown.jpg": "f79d7437",
 "assets/Exercises/web/nordic-hamstring-curl.jpg": "4c881710",
 "assets/Exercises/web/one-arm-dumbbell-row.jpg": "613d12c5",
 "assets/Exercises/web/overhead-cable-triceps-extension.jpg": "6dd47ba4",
 "assets/Exercises/web/overhead-dumbbell-extension.jpg": "61abc1ec",
 "assets/Exercises/web/overhead-tricep-extension.jpg": "f9742512",
 "assets/Exercises/web/pallof-press.jpg": "a9b419b1",
 "assets/Exercises/web/pec-deck.jpg": "0b1844c3",
 "assets/Exercises/web/pendlay-row.jpg": "fcd26844",
 "assets/Exercises/web/pendulum-squat.jpg": "1dc3f5ce",
 "assets/Exercises/web/pike-push-up.jpg": "b392070c",
 "assets/Exercises/web/pistol-squat.jpg": "e1a8d8db",
 "assets/Exercises/web/plank-shoulder-tap.jpg": "e50a6176",
 "assets/Exercises/web/plank.jpg": "96775280",
 "assets/Exercises/web/plate-pinch-hold.jpg": "64f7522c",
 "assets/Exercises/web/power-clean.jpg": "cdf1099f",
 "assets/Exercises/web/preacher-curl.jpg": "60a88f6e",
 "assets/Exercises/web/pull-ups.jpg": "a948c825",
 "assets/Exercises/web/push-press.jpg": "62f71d10",
 "assets/Exercises/web/push-ups.jpg": "ed27d145",
 "assets/Exercises/web/rack-pull.jpg": "dd01f494",
 "assets/Exercises/web/rear-delt-fly.jpg": "64b090fe",
 "assets/Exercises/web/recumbent-stationary-bike.jpg": "e4565db8",
 "assets/Exercises/web/renegade-row.jpg": "648c2e6e",
 "assets/Exercises/web/reverse-crunch.jpg": "5501c1ea",
 "assets/Exercises/web/reverse-curl.jpg": "aaa6054d",
 "assets/Exercises/web/reverse-hyperextension.jpg": "aa6a6af6",
 "assets/Exercises/web/reverse-lunge.jpg": "42d891ab",
 "assets/Exercises/web/reverse-pec-deck.jpg": "63395699",
 "assets/Exercises/web/reverse-wrist-curl.jpg": "3d247c42",
 "assets/Exercises/web/rowing-ergometer.jpg": "2d4ff059",
 "assets/Exercises/web/russian-twist.jpg": "2bf19dc8",
 "assets/Exercises/web/seated-cable-fly.jpg": "82969ecb",
 "assets/Exercises/web/seated-cable-row.jpg": "681d3916",
 "assets/Exercises/web/seated-calf-raise.jpg": "c3108b7d",
 "assets/Exercises/web/seated-dumbbell-shoulder-press.jpg": "c5e5806e",
 "assets/Exercises/web/seated-leg-curl.jpg": "d5d76154",
 "assets/Exercises/web/seated-machine-chest-press.jpg": "53d2267b",
 "assets/Exercises/web/seated-machine-row.jpg": "2128fd1b",
 "assets/Exercises/web/shrugs.jpg": "01873801",
 "assets/Exercises/web/side-plank.jpg": "3e06b2da",
 "assets/Exercises/web/single-arm-cable-pushdown.jpg": "1ab64adb",
 "assets/Exercises/web/single-arm-cable-row.jpg": "ddd1b0eb",
 "assets/Exercises/web/single-arm-dumbbell-row.jpg": "8427fd86",
 "assets/Exercises/web/single-arm-lat-pulldown.jpg": "e52f532d",
 "assets/Exercises/web/single-leg-calf-raise.jpg": "bde4d5b7",
 "assets/Exercises/web/single-leg-glute-bridge.jpg": "7df794f7",
 "assets/Exercises/web/single-leg-press.jpg": "447a9ec8",
 "assets/Exercises/web/single-leg-romanian-deadlift.jpg": "7c793c20",
 "assets/Exercises/web/sissy-squat.jpg": "c4e2829e",
 "assets/Exercises/web/sit-up.jpg": "ca438cc7",
 "assets/Exercises/web/skierg.jpg": "9790a210",
 "assets/Exercises/web/sled-pull-drag.jpg": "718c91dc",
 "assets/Exercises/web/sled-push.jpg": "85bd2947",
 "assets/Exercises/web/smith-machine-bench-press.jpg": "4755246a",
 "assets/Exercises/web/smith-machine-squat.jpg": "f74f3dd3",
 "assets/Exercises/web/spider-curl.jpg": "d818912a",
 "assets/Exercises/web/split-squat.jpg": "6cb7b533",
 "assets/Exercises/web/stairs.jpg": "797dff7c",
 "assets/Exercises/web/standing-barbell-overhead-press.jpg": "44131917",
 "assets/Exercises/web/standing-cable-fly-crossover.jpg": "c284206d",
 "assets/Exercises/web/standing-calf-raise.jpg": "6821bf85",
 "assets/Exercises/web/standing-dumbbell-curl.jpg": "202e93f2",
 "assets/Exercises/web/standing-leg-curl.jpg": "42400e7f",
 "assets/Exercises/web/standing-quadriceps-stretch.jpg": "3c0416d9",
 "assets/Exercises/web/step-up.jpg": "8ab4432b",
 "assets/Exercises/web/stiff-legged-deadlift.jpg": "470a271e",
 "assets/Exercises/web/straight-arm-cable-pulldown.jpg": "715d9b4d",
 "assets/Exercises/web/suitcase-carry.jpg": "1b95c6a8",
 "assets/Exercises/web/sumo-deadlift.jpg": "4c222fd1",
 "assets/Exercises/web/superman.jpg": "f4185b54",
 "assets/Exercises/web/thoracic-rotation-open-book.jpg": "fec90070",
 "assets/Exercises/web/trap-bar-deadlift.jpg": "db828726",
 "assets/Exercises/web/treadmill-run.jpg": "fa2b3c3c",
 "assets/Exercises/web/treadmill-walk.jpg": "45e148b5",
 "assets/Exercises/web/tricep-pushdown.jpg": "ec3fdb45",
 "assets/Exercises/web/tricep-rope-pushdown.jpg": "acc3bf0b",
 "assets/Exercises/web/turkish-get-up.jpg": "60199126",
 "assets/Exercises/web/underhand-lat-pulldown.jpg": "e2c1f552",
 "assets/Exercises/web/upper-body-ergometer.jpg": "c4a9ce52",
 "assets/Exercises/web/upright-row.jpg": "aae7b1ad",
 "assets/Exercises/web/upright-stationary-bike.jpg": "4d25c915",
 "assets/Exercises/web/v-up.jpg": "571249f1",
 "assets/Exercises/web/walking-lunges-with-dumbbells.jpg": "cbe3632e",
 "assets/Exercises/web/wall-ball.jpg": "2875373c",
 "assets/Exercises/web/wall-sit.jpg": "af1b9627",
 "assets/Exercises/web/weighted-plank.jpg": "fa68361c",
 "assets/Exercises/web/wide-stance-goblet-squat.jpg": "a4da6f64",
 "assets/Exercises/web/worlds-greatest-stretch.jpg": "d9c10522",
 "assets/Exercises/web/wrist-curl.jpg": "25008a7c",
 "assets/Exercises/web/wrist-roller.jpg": "4c425b49",
 "assets/Exercises/web/zottman-curl.jpg": "110e11ad"
};
/* BUILD:END */

const SHELL_CACHE = "ts-shell-" + BUILD_ID;
const IMG_CACHE = "ts-img-v2";

/* images are cached under "path?v=<content hash>", so a changed image is a
   cache miss and gets fetched again, while unchanged ones survive updates */
function imageKey(rel) {
  const v = IMAGE_FILES[rel];
  return v ? new URL(rel + "?v=" + v, self.registration.scope).href : null;
}
function relPath(url) {
  const scope = new URL(self.registration.scope).pathname;
  return url.pathname.indexOf(scope) === 0 ? decodeURIComponent(url.pathname.slice(scope.length)) : null;
}
async function cacheImages(rels) {
  const img = await caches.open(IMG_CACHE);
  for (let i = 0; i < rels.length; i += 6) {
    await Promise.all(rels.slice(i, i + 6).map(async (rel) => {
      const key = imageKey(rel);
      if (!key || (await img.match(key))) return;
      try {
        const res = await fetch(new Request(rel, { cache: "reload" }));
        if (res.ok) await img.put(key, res);
      } catch (err) {}
    }));
  }
}

self.addEventListener("install", (e) => {
  e.waitUntil((async () => {
    const shell = await caches.open(SHELL_CACHE);
    await shell.addAll(SHELL_FILES.map((u) => new Request(u, { cache: "reload" })));
    /* thumbnails up front (small); full-size images when viewed or when the app asks */
    await cacheImages(Object.keys(IMAGE_FILES).filter((p) => p.indexOf("/thumb/") !== -1));
  })());
});

self.addEventListener("activate", (e) => {
  e.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter((k) => k !== SHELL_CACHE && k !== IMG_CACHE).map((k) => caches.delete(k)));
    const img = await caches.open(IMG_CACHE);
    const wanted = new Set(Object.keys(IMAGE_FILES).map(imageKey));
    for (const req of await img.keys()) {
      if (!wanted.has(req.url)) await img.delete(req);
    }
    await self.clients.claim();
  })());
});

self.addEventListener("message", (e) => {
  if (e.data === "skipWaiting") self.skipWaiting();
  /* the app sends the full-size images its programmes use, for offline use at the gym */
  else if (e.data && e.data.type === "warm" && Array.isArray(e.data.urls)) {
    e.waitUntil(cacheImages(e.data.urls.filter((u) => typeof u === "string")));
  }
});

self.addEventListener("fetch", (e) => {
  const req = e.request;
  if (req.method !== "GET") return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;

  if (url.pathname.indexOf("/assets/Exercises/") !== -1) {
    const rel = relPath(url);
    const key = rel && imageKey(rel);
    if (!key) return;                     /* not a known image (e.g. a source PNG): plain network */
    e.respondWith((async () => {
      const img = await caches.open(IMG_CACHE);
      const hit = await img.match(key);
      if (hit) return hit;
      const res = await fetch(req);
      if (res.ok) img.put(key, res.clone());
      return res;
    })());
    return;
  }

  e.respondWith((async () => {
    const shell = await caches.open(SHELL_CACHE);
    const hit = await shell.match(req, { ignoreSearch: true }) || (req.mode === "navigate" ? await shell.match("./") : null);
    if (hit) return hit;
    try {
      return await fetch(req);
    } catch (err) {
      const any = await caches.match(req, { ignoreSearch: true });
      return any || Response.error();
    }
  })());
});
